import { Product } from "../../types";

export const productData: Product[] = [
    {
        id: '1',
        name: 'Tempered Glass Sheet',
        description: 'High-strength tempered glass for various applications',
        price: 120.50,
        stock: 40,
        image: 'https://image.made-in-china.com/202f0j00SwGVZLdPkbzk/Jinjing-Float-Glass-Supplier-3mm-10mm-Tempered-Glass-Sheet-for-Window.webp',
      },
      {
        id: '2',
        name: 'Laminated Glass Panel',
        description: 'Two layers of glass bonded with an interlayer for safety',
        price: 150.75,
        stock: 35,
        image: 'https://expresstoughening.com/wp-content/uploads/2020/11/Toughened-Laminated-Glass-Close.jpeg',
      },
      {
        id: '3',
        name: 'Mirror Glass',
        description: 'Silver-coated mirror glass for residential and commercial use',
        price: 85.00,
        stock: 50,
        image: 'https://images-na.ssl-images-amazon.com/images/I/51Cvg1TEPeL._SS400_.jpg',
      },
      {
        id: '4',
        name: 'Low-E Glass',
        description: 'Energy-efficient glass with low emissivity coating',
        price: 200.00,
        stock: 20,
        image: 'https://5.imimg.com/data5/EO/FK/MY-3140639/low-e-glass-250x250.jpg',
      },
      {
        id: '5',
        name: 'Glass Cutter Tool',
        description: 'Professional-grade glass cutter for precise cutting',
        price: 15.99,
        stock: 100,
        image: 'https://m.media-amazon.com/images/I/71LL2a-Q3dS._AC_SL1500_.jpg',
      },
      {
        id: '6',
        name: 'Glass Grinding Wheel',
        description: 'Durable grinding wheel for smooth glass finishing',
        price: 30.00,
        stock: 60,
        image: 'https://atozglassmaterials.com/wp-content/uploads/2023/02/20230223_151828-scaled.jpg',
      },
      {
        id: '7',
        name: 'Silicone Sealant',
        description: 'High-quality silicone sealant for glass bonding',
        price: 8.99,
        stock: 200,
        image: 'https://static-01.daraz.lk/p/2d57fee872de31154d3d75588e97c1b3.jpg',
      },
      {
        id: '8',
        name: 'Glass Adhesive UV Glue',
        description: 'Strong UV glue for seamless glass bonding',
        price: 25.50,
        stock: 80,
        image: 'https://m.media-amazon.com/images/I/71MwYNdbw3L._SL1500_.jpg',
      },
      {
        id: '9',
        name: 'Glass Edge Polishing Machine',
        description: 'Industrial machine for smooth glass edge polishing',
        price: 5000.00,
        stock: 5,
        image: 'https://image.made-in-china.com/2f0j00fYVRtBGsFHpg/Glass-Edge-Polishing-Machine-Maximum-Processing-Size-1500-1200mm.webp',
      },
      {
        id: '10',
        name: 'Glass Etching Cream',
        description: 'Chemical cream for glass etching designs',
        price: 12.50,
        stock: 90,
        image: 'https://5.imimg.com/data5/ANDROID/Default/2023/1/VJ/XV/JA/113970693/product-jpeg-500x500.jpg',
      },
      {
        id: '11',
        name: 'Insulated Glass Unit',
        description: 'Double-glazed glass panel for thermal insulation',
        price: 180.00,
        stock: 25,
        image: 'https://5.imimg.com/data5/SELLER/Default/2024/12/475704507/HN/OV/AS/4974982/insulated-glass-unit.jpeg',
      },
      {
        id: '12',
        name: 'Glass Cleaning Solution',
        description: 'Specialized solution for streak-free glass cleaning',
        price: 6.99,
        stock: 150,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS34JpAW2ylqpZ_C5diuuVmg95j_WRIX1y3PA&s',
      },
      {
        id: '13',
        name: 'Glass Vacuum Lifter',
        description: 'Heavy-duty vacuum lifter for handling large glass panels',
        price: 750.00,
        stock: 10,
        image: 'https://image.made-in-china.com/318f0j00PQnYjIHygLoU/glass-lifter-mp4.webp',
      },
      {
        id: '14',
        name: 'Glass Drilling Machine',
        description: 'Precision machine for drilling holes in glass',
        price: 2500.00,
        stock: 3,
        image: 'https://image.made-in-china.com/2f0j00gCuWywNhGiqJ/Huatian-Glass-Machines-Horizontal-Glass-Drilling-Machine-HBZ2120-K50.jpg',
      },
      {
        id: '15',
        name: 'Frosted Glass Panel',
        description: 'Opaque frosted glass for privacy applications',
        price: 135.00,
        stock: 30,
        image: 'https://image.made-in-china.com/202f0j00eYGRaDUcjkur/4mm-5mm-Sandblasted-Frosted-Glass-Panels.webp',
      },
    //   {
    //     id: '16',
    //     name: 'Anti-Reflective Glass',
    //     description: 'Glass with reduced reflection for display cases',
    //     price: 220.00,
    //     stock: 15,
    //     image: 'https://via.placeholder.com/400',
    //   },
    //   {
    //     id: '17',
    //     name: 'Bulletproof Glass',
    //     description: 'Laminated and toughened glass for security purposes',
    //     price: 2500.00,
    //     stock: 5,
    //     image: 'https://via.placeholder.com/400',
    //   },
    //   {
    //     id: '18',
    //     name: 'Ceramic Frit Glass',
    //     description: 'Decorative glass with ceramic frit printing',
    //     price: 180.00,
    //     stock: 20,
    //     image: 'https://via.placeholder.com/400',
    //   },
    //   {
    //     id: '19',
    //     name: 'Glass Beads for Sandblasting',
    //     description: 'High-quality glass beads for surface finishing',
    //     price: 50.00,
    //     stock: 75,
    //     image: 'https://via.placeholder.com/400',
    //   },
    //   {
    //     id: '20',
    //     name: 'Glass Railing System',
    //     description: 'Modern frameless glass railing for staircases',
    //     price: 1200.00,
    //     stock: 8,
    //     image: 'https://via.placeholder.com/400',
    //   },
    //   {
    //     id: '21',
    //     name: 'Toughened Glass Door',
    //     description: 'High-strength glass door with aluminum frame',
    //     price: 750.00,
    //     stock: 10,
    //     image: 'https://via.placeholder.com/400',
    //   },
    //   {
    //     id: '22',
    //     name: 'UV Protective Glass',
    //     description: 'Glass with UV blocking coating for protection',
    //     price: 250.00,
    //     stock: 18,
    //     image: 'https://via.placeholder.com/400',
    //   },
    //   {
    //     id: '23',
    //     name: 'Smart Glass',
    //     description: 'Switchable privacy glass controlled electronically',
    //     price: 3000.00,
    //     stock: 4,
    //     image: 'https://via.placeholder.com/400',
    //   },
    //   {
    //     id: '24',
    //     name: 'Fire-Resistant Glass',
    //     description: 'Tempered and laminated glass for fire resistance',
    //     price: 900.00,
    //     stock: 7,
    //     image: 'https://via.placeholder.com/400',
    //   },
    //   {
    //     id: '25',
    //     name: 'Decorative Stained Glass',
    //     description: 'Handcrafted stained glass for artistic applications',
    //     price: 400.00,
    //     stock: 15,
    //     image: 'https://via.placeholder.com/400',
    //   }
];